print("Welcome to the Band Name Generator")
print("What's the name of the city you grew up in?")
cityName = input()
print("What's your pet's name?")
petName = input()
print("Your band name could be " + cityName + " " + petName)
